# Docs: <https://git.io/JP3tm>

blank_issues_enabled: false

contact_links:
  - name: ðŸ—£ Ask a Question, Discuss
    url: https://github.com/tarampampam/error-pages/discussions
    about: Feel free to ask anything

  - name: ðŸŒ€ I have a question about Traefik..
    url: https://community.traefik.io/
    about: In this case - ask in the Traefik community
