# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: ðŸ“š Documentation

on:
  push:
    branches: [master, main]
    paths: ['README.md']

jobs:
  docker-hub-description:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
          repository: tarampampam/error-pages
